<a href="https://colab.research.google.com/github/ANUPAM7209/machine-learning/blob/main/Ordinal_Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder , OrdinalEncoder

In [ ]:
df = pd.read_csv('covid_toy.csv')

In [ ]:
df.head(5)

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2 )

In [ ]:
X_train.head(5)

    age  gender  fever   cough       city
0    60    Male  103.0    Mild    Kolkata
57   49  Female   99.0  Strong  Bangalore
54   60  Female   99.0    Mild     Mumbai
12   25  Female   99.0  Strong    Kolkata
19   42  Female    NaN  Strong  Bangalore

#Simple way

In [ ]:
si = SimpleImputer(strategy='mean')
X_train_si = si.fit_transform(X_train[['fever']])

X_test_si = si.transform(X_test[['fever']])

X_train_si.shape

(80, 1)

In [ ]:
ohe = OrdinalEncoder(categories=[['Mild', 'Strong']])
X_train_cough = ohe.fit_transform(X_train[['cough']])

X_test_cough =  ohe.transform(X_train[['cough']])

X_train_cough.shape

(80, 1)

In [ ]:
oe = OneHotEncoder(drop = 'first' , sparse_output = False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

# also the test data
X_test_gender_city = ohe.transform(X_test[['gender','city']])

X_train_gender_city.shape

ValueError: Shape mismatch: if categories is an array, it has to be of shape (n_features,).